# It may be tempting to add parens around each individual clause in this expression, but Travis then builds pushes anyway
if: branch = master OR branch =~ ^release/ OR tag IS present
language: go
go: 1.12
sudo: true # give us 7.5GB and >2 bursted cores.
git:
  depth: false
before_install:
    - git clone https://github.com/pulumi/scripts ${GOPATH}/src/github.com/pulumi/scripts
    - source ${GOPATH}/src/github.com/pulumi/scripts/ci/prepare-environment.sh
    - source ${PULUMI_SCRIPTS}/ci/keep-failed-tests.sh
install:
    # Install Pulumi and resource plugins.
    - source ${PULUMI_SCRIPTS}/ci/install-common-toolchain.sh
    - curl -L https://get.pulumi.com/ | bash -s -- --version 0.17.9
    - export PATH=$HOME/.pulumi/bin:$PATH
    - pulumi plugin install resource aws 0.18.3
    - pulumi plugin install resource azure 0.18.2
    - pulumi plugin install resource gcp 0.18.5
    - pulumi plugin install resource terraform-template 0.15.0
    - pulumi plugin install resource random 0.5.2

    # Install Terraform.
    - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip
    - unzip /tmp/terraform.zip -d /tmp
    - mv /tmp/terraform ~/bin
    - export PATH="~/bin:$PATH"
before_script:
    - ${PULUMI_SCRIPTS}/ci/ensure-dependencies
script:
    - ${PULUMI_SCRIPTS}/ci/heartbeat-with-timestamps& HEARTBEAT_PID=$!
    - make travis_${TRAVIS_EVENT_TYPE}
    - kill $HEARTBEAT_PID
after_failure:
    - ${PULUMI_SCRIPTS}/ci/upload-failed-tests
notifications:
    webhooks: https://ufci1w66n3.execute-api.us-west-2.amazonaws.com/stage/travis
